{
 "title": "hyperflow testv3",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Disk write",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hyperflow_disc_write",
     "select": [
      [
       { "params": [ "write_KiB" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk read",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hyperflow_disc_read",
     "select": [
      [
       { "params": [ "read_KiB" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network: data send",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ec2_incance_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "hyperflow_connection_transferred",
     "select": [
      [
       { "params": [ "transferred_bytes_per_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "network: data received",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ec2_incance_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "hyperflow_connection_received",
     "select": [
      [
       { "params": [ "received_bytes_per_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Usage (%) per EC2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ec2_incance_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "hyperflow_cpu_usage_ec2",
     "select": [
      [
       { "params": [ "cpu_usage_percentage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Used memory  per EC2 (KiB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ec2_incance_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "hyperflow_memory_usage_ec2",
     "select": [
      [
       { "params": [ "used_memory_K" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Memory and CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hyperflow_worker_cpu",
     "select": [
      [
       { "params": [ "precentageCPU" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hyperflow_master_cpu",
     "select": [
      [
       { "params": [ "precentageCPU" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hyperflow_cluster_cpu",
     "select": [
      [
       { "params": [ "precentageCPU" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hyperflow_master_memory",
     "select": [
      [
       { "params": [ "precentageCPU" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hyperflow_worker_cpu",
     "select": [
      [
       { "params": [ "precentageCPU" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hyperflow_cluster_memory",
     "select": [
      [
       { "params": [ "precentageCPU" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Executions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Panel Title",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "workflow_stage" ], "type": "tag" },
      { "params": [ "hfId" ], "type": "tag" }
     ],
     "measurement": "execution_log",
     "query": "SELECT \"workflow_stage\" FROM \"execution_log\" WHERE   $timeFilter GROUP BY \"workflow_stage\"",
     "select": [
      [
       { "params": [ "workflow_stage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "hfId" ], "type": "tag" },
      { "params": [ "wfid" ], "type": "tag" }
     ],
     "measurement": "execution_log_sub_stage",
     "select": [
      [
       { "params": [ "workflow_stage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "alias": "procId $tag_procId",
     "groupBy": [
      { "params": [ "procId" ], "type": "tag" }
     ],
     "measurement": "execution_log",
     "select": [
      [
       { "params": [ "stage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sub stages",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "workerId" ], "type": "tag" }
     ],
     "measurement": "execution_log_sub_stage",
     "select": [
      [
       { "params": [ "stage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Workers",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "workerId" ], "type": "tag" }
     ],
     "measurement": "execution_log",
     "select": [
      [
       { "params": [ "stage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "downloading time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "execution_times",
     "select": [
      [
       { "params": [ "downloading_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "uploading time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "execution_times",
     "select": [
      [
       { "params": [ "uploading_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "execution time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "execution_times",
     "select": [
      [
       { "params": [ "execution_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "execution time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "execution_times",
     "select": [
      [
       { "params": [ "execution_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "runing time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "execution_times",
     "select": [
      [
       { "params": [ "runing_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "download time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "execution_times",
     "select": [
      [
       { "params": [ "downloading_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "upload time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "execution_times",
     "select": [
      [
       { "params": [ "uploading_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "rabbitmq",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Queue Length",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "hyperflow_rabbitmq_monitor",
     "select": [
      [
       { "params": [ "QueueLength" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "consumers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "consumer count",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hyperflow_rabbitmq_monitor",
     "select": [
      [
       { "params": [ "consumerCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ECS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ec2_instances",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hyperflow_monitor",
     "select": [
      [
       { "params": [ "ec2_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "worker instances",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hyperflow_monitor",
     "select": [
      [
       { "params": [ "worker_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alarms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "alarm status",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hyperflow_alarms",
     "select": [
      [
       { "params": [ "alarm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}