{
 "title": "hyperflow tests",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Panel Title",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "workflow_stage" ], "type": "tag" }
     ],
     "measurement": "execution_log",
     "query": "SELECT \"workflow_stage\" FROM \"execution_log\" WHERE   $timeFilter GROUP BY \"workflow_stage\"",
     "select": [
      [
       { "params": [ "workflow_stage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "measurement": "execution_log_sub_stage",
     "select": [
      [
       { "params": [ "workflow_stage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "alias": "procId $tag_procId",
     "groupBy": [
      { "params": [ "procId" ], "type": "tag" }
     ],
     "measurement": "execution_log",
     "select": [
      [
       { "params": [ "stage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sub stages",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "workerId" ], "type": "tag" }
     ],
     "measurement": "execution_log_sub_stage",
     "select": [
      [
       { "params": [ "stage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Workers",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "workerId" ], "type": "tag" }
     ],
     "measurement": "execution_log",
     "select": [
      [
       { "params": [ "stage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "downloading time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "execution_times",
     "select": [
      [
       { "params": [ "downloading_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "uploading time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "execution_times",
     "select": [
      [
       { "params": [ "uploading_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "execution time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "execution_times",
     "select": [
      [
       { "params": [ "execution_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "execution time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "execution_times",
     "select": [
      [
       { "params": [ "execution_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "runing time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "execution_times",
     "select": [
      [
       { "params": [ "runing_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "download time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "execution_times",
     "select": [
      [
       { "params": [ "downloading_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "upload time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "execution_times",
     "select": [
      [
       { "params": [ "uploading_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "rabbitmq",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Queue Length",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "hyperflow_rabbitmq_monitor",
     "select": [
      [
       { "params": [ "QueueLength" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "consumers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "consumer count",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hyperflow_rabbitmq_monitor",
     "select": [
      [
       { "params": [ "consumerCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ECS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ec2_instances",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hyperflow_monitor",
     "select": [
      [
       { "params": [ "ec2_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "worker instances",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hyperflow_monitor",
     "select": [
      [
       { "params": [ "worker_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alarms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "alarm status",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hyperflow_alarms",
     "select": [
      [
       { "params": [ "alarm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}