version: '2'

volumes:
  prometheus_data: {}
  
services:
  prometheus:
    image: prom/prometheus
    volumes:
    - .:/etc/prometheus/
    - prometheus_data:/prometheus
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    ports:
    - 9090:9090
  grafana:
    image: grafana/grafana
    ports:
    - 3000:3000
    user: "104"
    volumes:
    - ./gant-discrete-panel/:/var/lib/grafana/plugins/grafana-discrete-panel/
    - ./provisioning/:/etc/grafana/provisioning/
    environment:
      GF_USERS_DEFAULT_THEME: light

