global:
  scrape_interval:     1s
  evaluation_interval: 5s

  external_labels:
    monitor: 'hyperflow'

scrape_configs:

- job_name: 'pushgateway'
  static_configs:
  - targets: [
    'localhost:9091'
  ]
  honor_labels: true

- job_name: 'hyperflow-ec2-status-reporter'
  scrape_interval: 500ms
  static_configs:
  - targets: [
    'localhost:9100'
  ]

- job_name: 'hyperflow-master-monitor'
  static_configs:
  - targets: [
    'localhost:9101',
    'localhost:9102',
    'localhost:9103',
  ]
